name: Setup Node.js and Dependencies
description: 'Setup Node.js, restore cache, and install dependencies'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        cache: 'npm'
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Install dependencies
      run: npm ci
      shell: bash
