require('isomorphic-fetch');
require('abortcontroller-polyfill');

import PlatformClient from '@coveord/platform-client';
import {Config, Configuration} from '../config/config';
import {
  castEnvironmentToPlatformClient,
  castRegionToPlatformClient,
} from './environment';

export class AuthenticatedClient {
  public cfg: Config;
  constructor() {
    this.cfg = new Config(global.config.configDir);
  }

  async isLoggedIn() {
    const {accessToken} = await this.cfg.get();
    return accessToken !== undefined;
  }

  async isExpired() {
    try {
      const c = await this.getClient();
      await c.initialize();
      return false;
    } catch (e) {
      return true;
    }
  }

  async getClient(customConfig?: Partial<Configuration>) {
    const {environment, region, organization, accessToken} =
      await this.cfg.get();
    return new PlatformClient({
      environment: castEnvironmentToPlatformClient(
        customConfig?.environment || environment
      ),
      region: castRegionToPlatformClient(customConfig?.region || region),
      organizationId: customConfig?.organization || organization,
      accessToken: customConfig?.accessToken
        ? customConfig?.accessToken
        : accessToken!,
    });
  }

  async getAllOrgsUserHasAccessTo() {
    const platformClient = await this.getClient();
    return platformClient.organization.list();
  }

  async getUserHasAccessToOrg(org: string) {
    const orgs = await this.getAllOrgsUserHasAccessTo();
    return orgs.some((o) => o.id === org);
  }

  async createImpersonateApiKey(name: string) {
    const platformClient = await this.getClient();
    return await platformClient.apiKey.create({
      displayName: `cli-${name}`,
      description: 'Generated by the Coveo CLI',
      enabled: true,
      privileges: [
        {targetDomain: 'IMPERSONATE', targetId: '*', owner: 'SEARCH_API'},
      ],
    });
  }

  async getUserInfo() {
    const authenticatedClient = new AuthenticatedClient();
    const platformClient = await authenticatedClient.getClient();
    await platformClient.initialize();

    return platformClient.user.get();
  }
}

export enum AuthenticationStatus {
  LOGGED_IN,
  EXPIRED,
  LOGGED_OUT,
}

export async function getAuthenticationStatus() {
  const authenticatedClient = new AuthenticatedClient();

  if (!(await authenticatedClient.isLoggedIn())) {
    return AuthenticationStatus.LOGGED_OUT;
  }

  if (await authenticatedClient.isExpired()) {
    return AuthenticationStatus.EXPIRED;
  }

  return AuthenticationStatus.LOGGED_IN;
}
