// const axios = require('axios');
const {homedir} = require('os');
const {join} = require('path');
const {config} = require('dotenv');
config({path: join(homedir(), '.env')});

// TODO: CDX-98: URL should vary in function of the target environment.
// const platformHost = 'https://platformdev.cloud.coveo.com/rest/';

// function authHeader(accessToken) {
//   return {
//     headers: {
//       Authorization: `Bearer ${accessToken}`,
//     },
//   };
// }

// async function getOldApiKeys(orgId, accessToken) {
//   const apiKeysUrl = `${platformHost}organizations/${orgId}/apikeys`;
//   const response = await axios.get(apiKeysUrl, authHeader(accessToken));

//   const wasCreatedByTheCli = (key) =>
//     key.displayName?.startsWith(`cli-`) &&
//     key.description === 'Generated by the Coveo CLI';

//   const wasNotUsedToday = (key) =>
//     key.lastUsedDate && key.lastUsedDate > 24 * 60 * 60 * 1000;

//   return response.data.filter(wasCreatedByTheCli).filter(wasNotUsedToday);
// }

// async function deleteApiKeys(orgId, accessToken, apiKeysToDelete) {
//   for (let i = 0; i < apiKeysToDelete.length; i++) {
//     const apiKey = apiKeysToDelete[i];
//     const apiKeyUrl = `${platformHost}organizations/${orgId}/apikeys/${apiKey.id}`;
//     console.log(`Deleting ${apiKey.displayName}`);
//     await axios.delete(apiKeyUrl, authHeader(accessToken));
//   }
//   console.log(`\nDeleted ${apiKeysToDelete.length} API keys`);
// }

async function main() {
  // const testOrgId = process.env.TEST_ORG_ID;
  // const accessToken = process.env.ACCESS_TOKEN;
  // const testRunId = process.env.TEST_RUN_ID;
  console.log('*********************');
  console.log(process.env.TEST_RUN_ID);
  console.log('*********************');

  // const apiKeys = await getOldApiKeys(testOrgId, accessToken);
  // await deleteApiKeys(testOrgId, accessToken, apiKeys);
}

main();
