name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    name: Lint
    runs-on: 'ubuntu-latest'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - uses: ./.github/actions/setup-node
      - name: Lint
        run: npm run lint
  build:
    name: Unit Tests
    runs-on: 'ubuntu-latest'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - uses: ./.github/actions/setup-node
      - name: Build
        run: npm run build
      - name: Tests
        run: npm test
