name: 'Delete Test API Keys'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      ORG_ID: ${{ secrets.ORG_ID }}
      PLATFORM_API_KEY: ${{ secrets.PLATFORM_API_KEY }}
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      - uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2
        with:
          node-version: '16'
      - run: npm i
      - run: node ./scripts/delete-api-keys.js --olderThan 1d
