name: 'Delete Test API Keys'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * SAT'

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TEST_ORG_ID: ${{ secrets.ORG_ID }}
      ACCESS_TOKEN: ${{ secrets.PLATFORM_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i
      - run: node ./scripts/delete-api-keys.js --olderThan 1d
