name: Merge Bot JS

on:
  issue_comment:
    types: [edited]
  pull_request:
    types: [opened]

jobs:
  Merge:
    if: ${{ github.event_name == 'pull_request' || github.event.issue.pull_request }}
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
      - name: Run the Bot
        run: npx @coveo/merge-bot
