name: Merge Bot JS

on:
  issue_comment:
    types: [edited]
  pull_request:
    types: [opened]

jobs:
  Merge:
    if: ${{ github.event_name == 'pull_request' || github.event.issue.pull_request }}
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      - name: Run the Bot
        run: npx @coveo/merge-bot
