name: oclif pack

on: push

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: $${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: short-hash
        id: short_hash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)" 
      - name: create-release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.short_hash.sha_short }}
          release_name: Release ${{ steps.short_hash.sha_short }}
          draft: false
          prerelease: false

  package-osx:
    name: Package cli for OSX
    runs-on: macos-latest
    needs: create-release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Setup
        run: npm run setup
      - name: oclif-dev package
        working-directory: ./packages/cli
        run: npx @oclif/dev-cli pack:macos
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: ./packages/cli/dist/macos/coveo-v0.0.0.pkg
          asset_name: coveo-v0.0.0.pkg
          asset_content_type: application/zip

  package-linux:
    name: Package cli for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Setup
        run: npm run setup
      - name: oclif-dev package
        working-directory: ./packages/cli
        run: npx @oclif/dev-cli pack:deb

  package-windows:
    name: Package cli for Windows
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Setup
        run: npm run setup
      - name: oclif-dev package
        working-directory: ./packages/cli
        run: |
          sudo apt-get update
          sudo apt-get install nsis          
          sudo apt-get install p7zip-full
          npx @oclif/dev-cli pack:win
      - name: Upload Release X64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./packages/cli/dist/win/coveo-v0.0.0-x64.exe
          asset_name: coveo-v0.0.0-x64.exe
          asset_content_type: application/zip
      - name: Upload Release X86
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./packages/cli/dist/win/coveo-v0.0.0-x86.exe
          asset_name: coveo-v0.0.0-x86.exe
          asset_content_type: application/zip
  
    
