name: oclif pack

on: push

jobs:
  package-osx:
    name: Package cli for OSX
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Setup
        run: npm run setup
      - name: oclif-dev package
        working-directory: ./packages/cli
        run: npx @oclif/dev-cli pack:macos
  package-linux:
    name: Package cli for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Setup
        run: npm run setup
      - name: oclif-dev package
        working-directory: ./packages/cli
        run: npx @oclif/dev-cli pack:deb
  package-windows:
    name: Package cli for Windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Setup
        run: npm run setup
      - name: oclif-dev package
        working-directory: ./packages/cli
        run: |
          sudo apt-get update
          sudo apt-get install nsis          
          sudo apt-get install p7zip-full
          npx @oclif/dev-cli pack:win
  
    
