name: 'package-lock.json version validator'

on:
  push:
    branches: [master]
    paths-ignore:
      - 'package-lock.json'
  pull_request:
    branches: [master]
    paths-ignore:
      - 'package-lock.json'

permissions:
  contents: read

jobs:
  lockfile-version:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - run: exit 0
