name: 'package-lock.json version validator'

on:
  push:
    branches: [master]
    paths:
      - 'package-lock.json'
  pull_request:
    branches: [master]
    paths:
      - 'package-lock.json'

jobs:
  lockfile-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2
      - name: Check lockfileVersion of all package-lock.json
        run: node scripts/check-lockfile-versions.js $(find ./ -xdev -wholename '**/package-lock.json')
