name: 'package-lock.json root validator'

on:
  push:
    branches: [master]
    paths-ignore:
      - '**/package-lock.json'
      - '!package-lock.json'
  pull_request:
    branches: [master]
    paths-ignore:
      - '**/package-lock.json'
      - '!package-lock.json'

jobs:
  lockfile-outside-of-root:
    runs-on: macos-latest
    steps:
      - run: exit 0
