name: 'package-lock.json version validator'

on:
  push:
    branches: [master]
    paths:
      - 'package-lock.json'
  pull_request:
    branches: [master]
    paths:
      - 'package-lock.json'

jobs:
  lockfile-version:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Check lockfileVersion of all package-lock.json
        run: node scripts/check-lockfile-versions.js $(find ./ -xdev -wholename '**/package-lock.json')
