name: 'package-lock.json version validator'

on:
  push:
    branches: [master]
    paths:
      - 'package-lock.json'
  pull_request:
    branches: [master]
    paths:
      - 'package-lock.json'

permissions:
  contents: read

jobs:
  lockfile-version:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - name: Check lockfileVersion of all package-lock.json
        run: node scripts/check-lockfile-versions.js $(find ./ -xdev -wholename '**/package-lock.json')
