name: PrTitleSemanticLint
on:
  pull_request:
    branches: [master]
    types: [opened, edited, synchronize, reopened]
jobs:
  Lint:
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Ensure PR Title is Semantic
        run: |
          npm ci
          npx @coveo/is-pr-title-semantic
