name: PrTitleSemanticLint
on:
  pull_request:
    branches: [master]
    types: [opened, edited, synchronize, reopened]
jobs:
  Lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3

      - name: Semantic Pull Request
        uses: step-security/action-semantic-pull-request@9142b539761b0ed6761de569f3a5020a7462a7f3
        with:
          requireScope: 'false'
