name: PrTitleSemanticLint
on:
  pull_request:
    branches: [master]
    types: [opened, edited, synchronize, reopened]
jobs:
  Lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Semantic Pull Request
        uses: step-security/action-semantic-pull-request@9142b539761b0ed6761de569f3a5020a7462a7f3
        with:
          requireScope: 'false'
