name: PR Robot
on:
  - pull_request

jobs:
  run-script:
    runs-on: ubuntu-24.04
    env:
      GITHUB_CREDENTIALS: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - run: npm i
      - run: npm run pr:report
