name: PR Robot
on:
  - pull_request

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_CREDENTIALS: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - run: npm i
      - run: npm run pr:report
