name: Create release

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  release:
    concurrency:
      group: release-${{ github.ref }}
      cancel-in-progress: false
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          app-id: ${{ secrets.RELEASER_APP_ID }}
          private-key: ${{ secrets.RELEASER_PRIVATE_KEY }}
          owner: coveo
          repositories: 'cli'

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}

      - uses: ./.github/actions/setup-node

      - name: Create release PR or publish
        id: changesets
        uses: step-security/changeset-action@6ddf46283ed49170eb6ca2179818f7d2a0ae687c # v1.9.0
        with:
          version: npm run version-packages
          publish: npm run release
          title: 'ci(changesets): version packages'
          commit: 'ci(changesets): version packages'
          commitMode: github-api
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
