name: 'Renovate Config Validator'

on:
  push:
    branches: [master]
    paths:
      - 'renovate.json'
  pull_request:
    branches: [master]
    paths:
      - 'renovate.json'

permissions:
  contents: read

jobs:
  renovate-config:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - name: Check Renovate config
        run: |
          npm i renovate
          node_modules/.bin/renovate-config-validator
