name: Refresh E2E Snapshots
on:
  workflow_dispatch:

jobs:
  e2e-setup-login:
    if: ${{ github.ref != 'refs/heads/main' }}
    name: End-to-end login
    runs-on: 'ubuntu-latest'
    outputs:
      cliConfigJson: ${{ steps.setup.outputs.cliConfigJson}}
    env:
      # Platform environment to log into for the e2e tests.
      PLATFORM_ENV: 'stg'
      # Username used to log into the organization whose ID is stored in the ORG_ID variable
      PLATFORM_USER_NAME: ${{ secrets.PLATFORM_USER_NAME }}
      # Password used to log into the organization whose ID is stored in the ORG_ID variable
      PLATFORM_USER_PASSWORD: ${{ secrets.PLATFORM_USER_PASSWORD }}
      # API key to delete all the API keys created by the e2e tests
      PLATFORM_API_KEY: ${{ secrets.PLATFORM_API_KEY }}
      # ID of the organization to log into for the e2e tests
      ORG_ID: ${{ secrets.ORG_ID }}
      # ID of the test run to identify resources to teardown.
      TEST_RUN_ID: 'id${{ matrix.os }}-${{ github.sha }}-${{ github.run_attempt }}g'
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: ${{matrix.node}}
          cache: 'npm'
      - name: Install locked NPM version.
        # TODO: CDX-1010 | Remove in CDX-1010.
        run: npm i -g npm@8.10.0
      - name: Install dependencies
        run: npm ci
      # `coveo auth:login` is always opening the default browser of the user, this ensure that the default browser is Chrome and that it'll be able to open by setting a X Display as the default Display
      - name: Prepare Google Chrome
        run: |
          Xvfb :1 -screen 0 1024x768x16 & sleep 1
          xdg-settings set default-web-browser google-chrome.desktop
      - name: Build
        run: npm run build
      - name: Setup E2E tests
        env:
          DISPLAY: ':1'
        run: node -r ts-node/register/transpile-only packages/cli-e2e/setup/ci-login.ts
      - name: Encode & Output config
        id: setup
        run: |
          echo "${{ secrets.E2E_TOKEN_PASSPHRASE }}" | gpg -a --batch --passphrase-fd 0 --symmetric --cipher-algo AES256 --output encodedConfig $CLI_CONFIG_PATH
          echo "::set-output name=cliConfigJson::$(base64 -w 0 encodedConfig)"
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        if: always()
        with:
          name: e2e-login-publish-artifacts
          path: ./packages/cli-e2e/artifacts
  e2e-setup-verdaccio:
    if: ${{ github.ref != 'refs/heads/main' }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    name: End-to-end publish packages
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: ${{matrix.node}}
          cache: 'npm'
      - uses: actions/cache@f4278025ab0f432ce369118909e46deec636f50c # tag=v3
        if: ${{matrix.os == 'ubuntu-latest'}}
        with:
          path: packages/cli-e2e/verdaccio
          key: verdaccio-${{matrix.os}}-${{ github.sha }}-${{ github.run_attempt }}
      - uses: actions/cache@f4278025ab0f432ce369118909e46deec636f50c # tag=v3
        if: ${{matrix.os == 'windows-latest'}}
        with:
          path: packages\cli-e2e\verdaccio
          key: verdaccio-${{matrix.os}}-${{ github.sha }}-${{ github.run_attempt }}
      - name: Install locked NPM version.
        # TODO: CDX-1010 | Remove in CDX-1010.
        run: npm i -g npm@8.10.0
      - run: npm ci
      - name: Build
        run: npm run build
      - name: Setup E2E tests
        run: node -r ts-node/register/transpile-only packages/cli-e2e/setup/ci-verdaccio.ts
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        if: always()
        with:
          name: ${{matrix.os}}-verdaccio-publish-artifacts
          path: ./packages/cli-e2e/artifacts
  e2e:
    if: ${{ github.ref != 'refs/heads/main' }}
    name: End-to-end tests
    runs-on: ${{matrix.os}}
    needs: [e2e-setup-login, e2e-setup-verdaccio]
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        node: [16]
        spec: ['atomic.specs.linux.ts', 'atomic.specs.windows.ts']
        # TODO: fix auth spec with windows
        exclude:
          - os: windows-latest
            spec: atomic.specs.linux.ts
          - os: ubuntu-latest
            spec: atomic.specs.windows.ts
    env:
      # Platform environment to log into for the e2e tests.
      PLATFORM_ENV: 'stg'
      # Username used to log into the organization whose ID is stored in the ORG_ID variable
      PLATFORM_USER_NAME: ${{ secrets.PLATFORM_USER_NAME }}
      # Password used to log into the organization whose ID is stored in the ORG_ID variable
      PLATFORM_USER_PASSWORD: ${{ secrets.PLATFORM_USER_PASSWORD }}
      # API key to delete all the API keys created by the e2e tests
      PLATFORM_API_KEY: ${{ secrets.PLATFORM_API_KEY }}
      # ID of the organization to log into for the e2e tests
      ORG_ID: ${{ secrets.ORG_ID }}
      # ID of the test run to identify resources to teardown.
      TEST_RUN_ID: 'id${{ matrix.os }}-${{ github.sha }}-${{ github.run_attempt }}g'
      COVEO_DISABLE_AUTOUPDATE: true
      CLI_CONFIG_JSON: ${{needs.e2e-setup-login.outputs.cliConfigJson}}
    steps:
      - name: Setup runner
        if: ${{matrix.os == 'ubuntu-latest'}}
        # Ensure we can use as many file watcher as we want. see https://github.com/facebook/create-react-app/blob/master/docusaurus/docs/troubleshooting.md#npm-start-fail-due-to-watch-error
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Setup runner
        if: ${{matrix.os == 'windows-latest'}}
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: ${{matrix.node}}
          cache: 'npm'
      - uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6 # tag=v3
        with:
          cache: 'pip'
      - name: Install Mitmproxy through pip
        run: pip install -r packages/cli-e2e/mitmproxy/requirements.txt
      - name: Install locked NPM version.
        # TODO: CDX-1010 | Remove in CDX-1010.
        run: npm i -g npm@8.10.0
      - uses: actions/cache@f4278025ab0f432ce369118909e46deec636f50c # tag=v3
        if: ${{matrix.os == 'ubuntu-latest'}}
        with:
          path: packages/cli-e2e/verdaccio
          key: verdaccio-${{matrix.os}}-${{ github.sha }}-${{ github.run_attempt }}
          restore-keys: verdaccio-${{matrix.os}}-${{ github.sha }}
      - uses: actions/cache@f4278025ab0f432ce369118909e46deec636f50c # tag=v3
        if: ${{matrix.os == 'windows-latest'}}
        with:
          path: packages\cli-e2e\verdaccio
          key: verdaccio-${{matrix.os}}-${{ github.sha }}-${{ github.run_attempt }}
          restore-keys: verdaccio-${{matrix.os}}-${{ github.sha }}
      - name: Decrypt config
        working-directory: packages/cli-e2e
        run: echo ${{needs.e2e-setup-login.outputs.cliConfigJson}} | base64 --decode | gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.E2E_TOKEN_PASSPHRASE }}" --output decrypted
      - run: npm ci
      - name: End-to-end Setup
        if: ${{matrix.os == 'ubuntu-latest'}}
        run: bash packages/cli-e2e/entrypoints/ci.sh
      - name: End-to-end Setup
        if: ${{matrix.os == 'windows-latest'}}
        run: packages/cli-e2e/entrypoints/ci.ps1
      - name: Tests
        if: ${{matrix.os == 'windows-latest'}}
        working-directory: packages/cli-e2e
        run: npm run jest:ci -- -u ${{matrix.spec}}
      - name: Tests
        if: ${{matrix.os == 'ubuntu-latest'}}
        env:
          DISPLAY: ':1'
        working-directory: packages/cli-e2e
        run: npm run jest:ci -- -u ${{matrix.spec}}
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        if: ${{matrix.os == 'windows-latest'}}
        with:
          name: ${{matrix.os}}-snap-artifact
          path: ./packages/cli-e2e/**/*.windows.ts.snap
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        if: ${{matrix.os == 'ubuntu-latest'}}
        with:
          name: ${{matrix.os}}-snap-artifact
          path: ./packages/cli-e2e/**/*.linux.ts.snap
  e2e-teardown:
    name: End-to-end teardown
    if: ${{ always() }}
    needs: [e2e, e2e-setup-login]
    runs-on: ubuntu-latest
    env:
      # Platform environment to log into for the e2e tests.
      PLATFORM_ENV: 'stg'
      # Username used to log into the organization whose ID is stored in the ORG_ID variable
      PLATFORM_USER_NAME: ${{ secrets.PLATFORM_USER_NAME }}
      # Password used to log into the organization whose ID is stored in the ORG_ID variable
      PLATFORM_USER_PASSWORD: ${{ secrets.PLATFORM_USER_PASSWORD }}
      # API key to delete all the API keys created by the e2e tests
      PLATFORM_API_KEY: ${{ secrets.PLATFORM_API_KEY }}
      # ID of the organization to log into for the e2e tests
      ORG_ID: ${{ secrets.ORG_ID }}
      # ID of the test run to identify resources to teardown.
      TEST_RUN_ID: '${{ github.sha }}-${{ github.run_attempt }}g'
      CLI_CONFIG_JSON: ${{needs.e2e-setup-login.outputs.cliConfigJson}}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          node-version: ${{matrix.node}}
          cache: 'npm'
      - name: Install locked NPM version.
        # TODO: CDX-1010 | Remove in CDX-1010.
        run: npm i -g npm@8.10.0
      - run: npm ci
      - name: Decrypt config
        run: echo ${{needs.e2e-setup-login.outputs.cliConfigJson}} | base64 --decode | gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.E2E_TOKEN_PASSPHRASE }}" --output decrypted
      - name: Delete test org
        env:
          DISPLAY: ':1'
        if: always()
        run: |
          Xvfb :1 -screen 0 1024x768x16 & sleep 1
          xdg-settings set default-web-browser google-chrome.desktop
          node -r ts-node/register/transpile-only packages/cli-e2e/cleaning.ts
          node ./scripts/cleaning/delete-orgs.js
      - name: Delete test API key
        if: always()
        run: node ./scripts/cleaning/delete-api-keys.js
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3
        with:
          name: windows-latest-snap-artifact
          path: ./packages/cli-e2e
      - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # tag=v3
        with:
          name: ubuntu-latest-snap-artifact
          path: ./packages/cli-e2e
      - run: git diff ./packages/cli-e2e/**/*.snap
        continue-on-error: true
      - name: Check for Jest Snapshots changes
        run: echo "::set-output name=exitCode::$(git diff --quiet ./packages/cli-e2e/**/*.snap ; echo $?)"
        id: has-changes
      - name: Commit artifacts
        if: ${{ steps.has-changes.outputs.exitCode == '1'}}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./packages/cli-e2e/**/*.snap
          git commit -m "update e2e snapshots" --no-verify
          git push
